[workspace]
authors = ["Nasir Nesirli <nasir.nesirli@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "sars-variant-hunter"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
seqkit = ">=2.12.0,<3"
bwa = ">=0.7.19,<0.8"
samtools = ">=1.23,<2"
bcftools = ">=1.23,<2"
